name: Feature request
description: Propose an enhancement for jest-llm-eval
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or features you've considered

